apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-queries-deployment
spec:
  selector:
    matchLabels:
      app: products-queries
  replicas: 2
  template:
    metadata:
      labels:
        app: products-queries
    spec:
      containers:
      - name: products-queries-container
        image: 1151386/products-queries
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        - containerPort: 5672
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: products-queries-service
spec:
  selector:
    app: products-queries
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
    nodePort: 30016
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30017
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: products-queries-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: products-queries
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50