apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry-app
spec:
  selector:
    matchLabels:
      app: serviceregistry-serviceregistry
  replicas: 1
  template:
    metadata:
      labels:
        app: serviceregistry-serviceregistry
    spec:
      containers:
        - name: service-registry-app
          image: 1151386/serviceregistry-serviceregistry:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production
---
apiVersion: v1
kind: Service
metadata:
  name: service-registry-app
spec:
  selector:
    app: serviceregistry-serviceregistry
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      nodePort: 30004
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30005
  type: NodePort