apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry-deployment
spec:
  selector:
    matchLabels:
      app: serviceregistry
  replicas: 1
  template:
    metadata:
      labels:
        app: serviceregistry
    spec:
      containers:
      - name: service-registry-container
        image: 1151386/serviceregistry
        imagePullPolicy: Never
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: service-registry-service
spec:
  selector:
    app: serviceregistry
  ports:
  - name: http
    port: 8761
    targetPort: 8761
    nodePort: 30005
  type: NodePort