apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
spec:
  selector:
    matchLabels:
      app: reviews
  replicas: 2
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
        - name: reviews
          image: 1151386/reviews:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.2"
              memory: "200k"
            requests:
              cpu: "0.1"
              memory: "100k"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-service-app
spec:
  selector:
    app: reviews
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30006
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reviews-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reviews
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50