apiVersion: apps/v1
kind: Deployment
metadata:
  name: votes-queries-deployment
spec:
  selector:
    matchLabels:
      app: votes-queries
  replicas: 2
  template:
    metadata:
      labels:
        app: votes-queries
    spec:
      containers:
      - name: votes-queries-container
        image: 1151386/votes-queries
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        - containerPort: 5672
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: votes-queries-service
spec:
  selector:
    app: votes-queries
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
    nodePort: 30020
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30021
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: votes-queries-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: votes-queries
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50