version: '3'

services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"
      - "15672:15672"