apiVersion: apps/v1
kind: Deployment
metadata:
  name: votes
spec:
  selector:
    matchLabels:
      app: votes
  replicas: 2
  template:
    metadata:
      labels:
        app: votes
    spec:
      containers:
        - name: votes
          image: 1151386/votes
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production
      restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: votes-service-app
spec:
  selector:
    app: votes
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30007
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: votes-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: votes
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50