apiVersion: apps/v1
kind: Deployment
metadata:
  name: votes-deployment
spec:
  restartPolicy: "OnFailure"
  maxRetries: "3"
  selector:
    matchLabels:
      app: votes
  replicas: 2
  template:
    metadata:
      labels:
        app: votes
    spec:
      containers:
      - name: votes-container
        image: 1151386/votes
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        - containerPort: 5672
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: votes-service
spec:
  selector:
    app: votes
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
    nodePort: 30009
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30008
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: votes-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: votes
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50