openapi: 3.0.1
info:
  title: ACME_PT
  version: 1.0.0
servers:
 -
  url: /
security:
 -
  default: []
paths:
  /produtos:
    get:
      parameters: []
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - Admin
         - User
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
    post:
      parameters: []
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - Admin
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /produtos/{sku}:
    get:
      parameters:
       -
        name: sku
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - Admin
         - User
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
    delete:
      parameters:
       -
        name: sku
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - Admin
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
    patch:
      parameters:
       -
        name: sku
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - Admin
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /produtos/designacao/{designacao}:
    get:
      parameters:
       -
        name: designacao
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - Admin
         - User
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /produtos/{sku}/criticas/{status}:
    get:
      parameters:
       -
        name: sku
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
       -
        name: status
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - Admin
         - User
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /criticas/pendente:
    get:
      parameters: []
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - Admin
         - User
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /produtos/{sku}/criticas:
    post:
      parameters:
       -
        name: sku
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - Admin
         - User
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /criticas/{criticaID}:
    delete:
      parameters:
       -
        name: criticaID
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - Admin
         - User
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /criticas/aceiterejeitada/{criticaID}:
    put:
      parameters:
       -
        name: criticaID
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - Admin
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /votos:
    get:
      parameters: []
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - Admin
         - User
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /votos/{voteID}:
    get:
      parameters:
       -
        name: voteID
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - Admin
         - User
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
    delete:
      parameters:
       -
        name: voteID
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - Admin
         - User
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
    patch:
      parameters:
       -
        name: voteID
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - Admin
         - User
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /critica/{criticaUuid}/votos:
    post:
      parameters:
       -
        name: criticaUuid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - Admin
         - User
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /semcritica/{sku}/votos:
    post:
      parameters:
       -
        name: sku
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - Admin
         - User
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /critica/{tipoDeVoto}/maisXvotos/{numeroDeVotos}:
    get:
      parameters:
       -
        name: tipoDeVoto
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
       -
        name: numeroDeVotos
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - Admin
         - User
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /critica/{tipoDeVoto}/menosXvotos/{numeroDeVotos}:
    get:
      parameters:
       -
        name: tipoDeVoto
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
       -
        name: numeroDeVotos
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - Admin
         - User
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /critica/quantidadePorUtilizador/{utilizador}:
    get:
      parameters:
       -
        name: utilizador
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - Admin
         - User
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /produtos/{tipoDeVoto}/maisDe/{percentagem}:
    get:
      parameters:
       -
        name: tipoDeVoto
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
       -
        name: percentagem
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - Admin
         - User
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /produtos/{tipoDeVoto}/menos/{percentagem}:
    get:
      parameters:
       -
        name: tipoDeVoto
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
       -
        name: percentagem
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - Admin
         - User
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /criticas/{utilizador}:
    get:
      parameters:
       -
        name: utilizador
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - Admin
         - User
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://test.com
          scopes:
            Admin: ""
            User: ""
          x-scopes-bindings:
            User: Internal/integration_dev
            Admin: admin
x-wso2-auth-header: Authorization
x-wso2-cors:
  corsConfigurationEnabled: false
  accessControlAllowOrigins:
   - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
   - authorization
   - Access-Control-Allow-Origin
   - Content-Type
   - SOAPAction
   - apikey
   - Internal-Key
  accessControlAllowMethods:
   - GET
   - PUT
   - POST
   - DELETE
   - PATCH
   - OPTIONS
x-wso2-production-endpoints:
  urls:
   - http://localhost:8290/ACME
  type: http
x-wso2-sandbox-endpoints:
  urls:
   - http://localhost:8290/ACME
  type: http
x-wso2-basePath: /acme_pt/1.0.0
x-wso2-transports:
 - http
 - https
x-wso2-response-cache:
  enabled: true
  cacheTimeoutInSeconds: 900
