type: operation_policy_specification
version: v4.2.0
data:
  category: Mediation
  name: ProductsLessVotePercentage
  version: v1
  displayName: ProductsLessVotePercentage
  description: ""
  applicableFlows:
   - request
   - response
   - fault
  supportedGateways:
   - Synapse
  supportedApiTypes:
   - HTTP
  policyAttributes: []
