version: '3.8'
# To run this file, execute the following command:
# docker compose -f {compose file name} up
# This create and starts the containers

services:
  loadbalancer:
    build: .
    container_name: LoadBalancer
    ports:
      - 8081:8080