apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer-deployment
spec:
  selector:
    matchLabels:
      app: load-balancer
  replicas: 1
  template:
    metadata:
      labels:
        app: load-balancer
    spec:
      containers:
      - name: load-balancer-container
        image: 1151386/load-balancer
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
spec:
  selector:
    app: load-balancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30003
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: load-balancer-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: load-balancer
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50